# Generated by Django 4.1.6 on 2023-02-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='hcbgev', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
